apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-grava-es
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fast-grava-es
  template:
    metadata:
      labels:
        app: fast-grava-es
    spec:
      containers:
      - name: app
        image: fast-grava-es:latest
        ports:
        - containerPort: 80
