import React, { useEffect, useRef, useState } from 'react';
import mermaid from 'mermaid';
import { Card } from "@/components/ui/card";
import { Copy, Check, BarChart3, Settings2 } from "lucide-react";
import { toast } from "sonner";

// Configure mermaid
mermaid.initialize({
  startOnLoad: true,
  theme: 'dark',
  securityLevel: 'loose',
  fontFamily: 'Inter, sans-serif'
});

interface MermaidDiagramProps {
  chart: string;
}

export const MermaidDiagram = ({ chart }: MermaidDiagramProps) => {
  const [svg, setSvg] = useState<string>('');
  const [error, setError] = useState<boolean>(false);
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const renderDiagram = async () => {
      if (!chart) return;
      try {
        const id = `mermaid-${Math.random().toString(36).substr(2, 9)}`;
        const { svg } = await mermaid.render(id, chart);
        setSvg(svg);
        setError(false);
      } catch (err) {
        console.error('Mermaid rendering failed:', err);
        setError(true);
      }
    };
    renderDiagram();
  }, [chart]);

  if (error) return null;

  return (
    <Card className="my-4 p-4 bg-muted/20 border-border/50 overflow-auto">
      <div 
        ref={containerRef}
        className="flex justify-center"
        dangerouslySetInnerHTML={{ __html: svg }} 
      />
    </Card>
  );
};

interface ParameterTableProps {
  data: string;
}

export const ParameterTable = ({ data }: ParameterTableProps) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(data);
    setCopied(true);
    toast.success("Dados copiados");
    setTimeout(() => setCopied(false), 2000);
  };

  // Basic parser for CSV-like or Table-like strings often generated by AI
  const rows = data.split('\n').filter(r => r.trim()).map(r => r.split('|').filter(c => c.trim()));

  if (rows.length < 2) return <pre className="text-xs bg-muted p-2 rounded">{data}</pre>;

  return (
    <Card className="my-4 overflow-hidden border-border/50">
      <div className="bg-muted/50 px-4 py-2 border-b border-border/50 flex justify-between items-center bg-gradient-to-r from-muted/50 to-transparent">
        <div className="flex items-center gap-3 text-[10px] font-black text-muted-foreground uppercase tracking-widest">
          <div className="p-1.5 rounded bg-primary/10">
            <Settings2 className="h-3 w-3 text-primary" />
          </div>
          PARÂMETROS TÉCNICOS EXTRAÍDOS
          <Badge variant="outline" className="text-[8px] h-4 border-primary/20 text-primary">SPC READY</Badge>
        </div>
        <div className="flex items-center gap-2">
          <button 
            onClick={() => {
              toast.success("Todos os parâmetros enviados para a máquina");
            }}
            className="text-[9px] font-black uppercase tracking-tighter text-primary hover:underline"
          >
            Sincronizar Tudo
          </button>
          <div className="w-px h-3 bg-border/50 mx-1" />
          <button onClick={handleCopy} className="hover:text-primary transition-colors p-1 rounded hover:bg-muted">
            {copied ? <Check className="h-3.5 w-3.5 text-green-500" /> : <Copy className="h-3.5 w-3.5" />}
          </button>
        </div>
      </div>
      <div className="overflow-x-auto custom-scrollbar">
        <table className="w-full text-[11px] text-left border-collapse">
          <thead>
            <tr className="bg-muted/30 border-b border-border/50">
              {rows[0].map((cell, i) => (
                <th key={i} className="px-4 py-2.5 font-black uppercase tracking-tighter text-muted-foreground">{cell.trim()}</th>
              ))}
              <th className="px-4 py-2.5 font-black uppercase tracking-tighter text-muted-foreground w-10">Ação</th>
            </tr>
          </thead>
          <tbody>
            {rows.slice(1).map((row, i) => (
              <tr key={i} className="border-b border-border/30 last:border-0 hover:bg-primary/5 transition-all group">
                {row.map((cell, j) => (
                  <td key={j} className="px-4 py-2 font-medium">{cell.trim()}</td>
                ))}
                <td className="px-4 py-2">
                  <button className="p-1 rounded bg-muted opacity-0 group-hover:opacity-100 hover:text-primary transition-all">
                    <Check className="h-3 w-3" />
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Card>
  );
};
