import React, { useEffect, useRef, useState } from 'react';
import mermaid from 'mermaid';
import { Card } from "@/components/ui/card";
import { Copy, Check, BarChart3, Settings2 } from "lucide-react";
import { toast } from "sonner";

// Configure mermaid
mermaid.initialize({
  startOnLoad: true,
  theme: 'dark',
  securityLevel: 'loose',
  fontFamily: 'Inter, sans-serif'
});

interface MermaidDiagramProps {
  chart: string;
}

export const MermaidDiagram = ({ chart }: MermaidDiagramProps) => {
  const [svg, setSvg] = useState<string>('');
  const [error, setError] = useState<boolean>(false);
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const renderDiagram = async () => {
      if (!chart) return;
      try {
        const id = `mermaid-${Math.random().toString(36).substr(2, 9)}`;
        const { svg } = await mermaid.render(id, chart);
        setSvg(svg);
        setError(false);
      } catch (err) {
        console.error('Mermaid rendering failed:', err);
        setError(true);
      }
    };
    renderDiagram();
  }, [chart]);

  if (error) return null;

  return (
    <Card className="my-4 p-4 bg-muted/20 border-border/50 overflow-auto">
      <div 
        ref={containerRef}
        className="flex justify-center"
        dangerouslySetInnerHTML={{ __html: svg }} 
      />
    </Card>
  );
};

interface ParameterTableProps {
  data: string;
}

export const ParameterTable = ({ data }: ParameterTableProps) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(data);
    setCopied(true);
    toast.success("Dados copiados");
    setTimeout(() => setCopied(false), 2000);
  };

  // Basic parser for CSV-like or Table-like strings often generated by AI
  const rows = data.split('\n').filter(r => r.trim()).map(r => r.split('|').filter(c => c.trim()));

  if (rows.length < 2) return <pre className="text-xs bg-muted p-2 rounded">{data}</pre>;

  return (
    <Card className="my-4 overflow-hidden border-border/50">
      <div className="bg-muted/50 px-4 py-2 border-b border-border/50 flex justify-between items-center">
        <div className="flex items-center gap-2 text-xs font-medium text-muted-foreground">
          <Settings2 className="h-3.5 w-3.5" />
          PARÂMETROS TÉCNICOS EXTRAÍDOS
        </div>
        <button onClick={handleCopy} className="hover:text-primary transition-colors">
          {copied ? <Check className="h-3.5 w-3.5 text-green-500" /> : <Copy className="h-3.5 w-3.5" />}
        </button>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full text-xs text-left">
          <thead>
            <tr className="bg-muted/30 border-b border-border/50">
              {rows[0].map((cell, i) => (
                <th key={i} className="px-4 py-2 font-semibold">{cell.trim()}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.slice(1).map((row, i) => (
              <tr key={i} className="border-b border-border/30 last:border-0 hover:bg-muted/20 transition-colors">
                {row.map((cell, j) => (
                  <td key={j} className="px-4 py-2">{cell.trim()}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Card>
  );
};
