-- Fix production_losses.operator_id FK to use ON DELETE SET NULL.
--
-- The original CREATE TABLE used a bare REFERENCES auth.users(id) with no ON
-- DELETE clause, which defaults to RESTRICT. This means deleting a user account
-- that has any production_losses rows throws a FK violation and prevents the
-- deletion — a user-management showstopper.
--
-- Fix: drop the auto-named constraint and recreate it with ON DELETE SET NULL
-- so that removing a user account nulls out the operator attribution on
-- historical records rather than blocking the deletion.
--
-- The constraint name is auto-generated by Postgres as
-- production_losses_operator_id_fkey (the standard <table>_<col>_fkey pattern).

ALTER TABLE public.production_losses
  DROP CONSTRAINT IF EXISTS production_losses_operator_id_fkey;

ALTER TABLE public.production_losses
  ADD CONSTRAINT production_losses_operator_id_fkey
  FOREIGN KEY (operator_id)
  REFERENCES auth.users(id)
  ON DELETE SET NULL;
