// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: async (url, options) => {
      const start = performance.now();
      try {
        const response = await fetch(url, options);
        const duration = performance.now() - start;
        
        // Capturar métricas de performance para telemetria interna
        if (url.toString().includes('postgrest') || url.toString().includes('rpc')) {
          const route = window.location.pathname;
          const method = options?.method || 'GET';
          
          import('@/lib/logger').then(({ logger }) => {
            if (!response.ok) {
              logger.error(`Falha na API Supabase (${response.status}): ${url.toString()}`, {
                status: response.status,
                url: url.toString(),
                route
              });
            } else if (duration > 1500) {
              logger.warn(`Query lenta detectada em ${route}: ${duration.toFixed(2)}ms`, {
                url: url.toString(),
                method,
                duration,
                route
              });
            }
          });
        }
        
        return response;
      } catch (error) {
        import('@/lib/logger').then(({ logger }) => {
          logger.critical(`Erro de rede/conectividade com Supabase: ${url.toString()}`, error);
        });
        throw error;
      }
    }
  }
});