// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: async (url, options) => {
      const start = performance.now();
      try {
        const response = await fetch(url, options);
        const duration = performance.now() - start;
        const urlString = url.toString();

        // Capturar métricas de performance para telemetria interna.
        // IMPORTANT: never instrument the telemetry table itself. The logger
        // persists into `error_logs` via this same client; logging a slow/failed
        // `error_logs` write would re-trigger the logger → another write →
        // self-amplifying cascade. Skip telemetry endpoints entirely.
        const isTelemetry = urlString.includes('error_logs');
        if (!isTelemetry && (urlString.includes('postgrest') || urlString.includes('rpc'))) {
          const route = window.location.pathname;
          const method = options?.method || 'GET';

          import('@/lib/logger').then(({ logger }) => {
            if (!response.ok) {
              logger.error(`Falha na API Supabase (${response.status}): ${urlString}`, {
                status: response.status,
                url: urlString,
                route
              });
            } else if (duration > 1500) {
              logger.warn(`Query lenta detectada em ${route}: ${duration.toFixed(2)}ms`, {
                url: urlString,
                method,
                duration,
                route
              });
            }
          });
        }

        return response;
      } catch (error) {
        // Skip telemetry endpoints to avoid the logging-of-logging cascade.
        if (!url.toString().includes('error_logs')) {
          import('@/lib/logger').then(({ logger }) => {
            logger.critical(`Erro de rede/conectividade com Supabase: ${url.toString()}`, error);
          });
        }
        throw error;
      }
    }
  }
});